[package]
name = "teastain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.6.5"
quick-xml = "0.28.2"
unicode-segmentation = "1.10.1"